const RAASI_DATA = [
  {
    id: 1,
    nameEn: "Mesha",
    nameTe: "మేషం (Aries)",
    lordEn: "Mars",
    lordTe: "కుజుడు (Kuja)",
    element: "Fire (అగ్ని)",
    symbol: "Ram (పొట్టేలు)",
    color: "from-red-500/30 to-orange-600/10",
    glowColor: "rgba(239, 68, 68, 0.4)",
    traits: "Enthusiastic, bold, ambitious, natural leaders, impulsive, and full of energy."
  },
  {
    id: 2,
    nameEn: "Vrishabha",
    nameTe: "వృషభం (Taurus)",
    lordEn: "Venus",
    lordTe: "శుక్రుడు (Shukra)",
    element: "Earth (భూమి)",
    symbol: "Bull (ఎద్దు)",
    color: "from-emerald-500/30 to-teal-600/10",
    glowColor: "rgba(16, 185, 129, 0.4)",
    traits: "Patient, reliable, artistic, lover of luxury, determined, and strongly grounded."
  },
  {
    id: 3,
    nameEn: "Mithuna",
    nameTe: "మిథునం (Gemini)",
    lordEn: "Mercury",
    lordTe: "బుధుడు (Budha)",
    element: "Air (వాయువు)",
    symbol: "Twins (మిథున జంట)",
    color: "from-cyan-500/30 to-blue-600/10",
    glowColor: "rgba(6, 182, 212, 0.4)",
    traits: "Expressive, intellectual, curious, witty, highly adaptable, and multi-talented."
  },
  {
    id: 4,
    nameEn: "Karka",
    nameTe: "కర్కాటకం (Cancer)",
    lordEn: "Moon",
    lordTe: "చంద్రుడు (Chandra)",
    element: "Water (జలం)",
    symbol: "Crab (పీత)",
    color: "from-slate-400/30 to-indigo-600/10",
    glowColor: "rgba(148, 163, 184, 0.4)",
    traits: "Intuitive, nurturing, emotional, deeply attached to home, protective, and sensitive."
  },
  {
    id: 5,
    nameEn: "Simha",
    nameTe: "సింహం (Leo)",
    lordEn: "Sun",
    lordTe: "సూర్యుడు (Surya)",
    element: "Fire (అగ్ని)",
    symbol: "Lion (సింహం)",
    color: "from-amber-500/30 to-yellow-600/10",
    glowColor: "rgba(245, 158, 11, 0.4)",
    traits: "Generous, proud, loyal, dramatic, natural-born leaders, and love being center-stage."
  },
  {
    id: 6,
    nameEn: "Kanya",
    nameTe: "కన్యా (Virgo)",
    lordEn: "Mercury",
    lordTe: "బుధుడు (Budha)",
    element: "Earth (భూమి)",
    symbol: "Virgin (కన్య)",
    color: "from-teal-500/30 to-green-600/10",
    glowColor: "rgba(20, 184, 166, 0.4)",
    traits: "Analytical, meticulous, helpful, health-conscious, practical, and highly organized."
  },
  {
    id: 7,
    nameEn: "Tula",
    nameTe: "తులా (Libra)",
    lordEn: "Venus",
    lordTe: "శుక్రుడు (Shukra)",
    element: "Air (వాయువు)",
    symbol: "Scales (త్రాసు)",
    color: "from-pink-500/30 to-rose-600/10",
    glowColor: "rgba(236, 72, 153, 0.4)",
    traits: "Diplomatic, fair-minded, social, lovers of harmony, artistic, and relationship-driven."
  },
  {
    id: 8,
    nameEn: "Vrishchika",
    nameTe: "వృశ్చికం (Scorpio)",
    lordEn: "Mars",
    lordTe: "కుజుడు (Kuja)",
    element: "Water (జలం)",
    symbol: "Scorpion (తేలు)",
    color: "from-red-600/30 to-purple-800/10",
    glowColor: "rgba(220, 38, 38, 0.4)",
    traits: "Passionate, secretive, powerful, highly intuitive, loyal, and fiercely determined."
  },
  {
    id: 9,
    nameEn: "Dhanu",
    nameTe: "ధనుస్సు (Sagittarius)",
    lordEn: "Jupiter",
    lordTe: "గురుడు (Guru)",
    element: "Fire (అగ్ని)",
    symbol: "Archer / Centaur (ధనుర్ధారి)",
    color: "from-yellow-600/30 to-amber-700/10",
    glowColor: "rgba(217, 119, 6, 0.4)",
    traits: "Optimistic, philosophical, freedom-loving, adventurous, and seekers of absolute truth."
  },
  {
    id: 10,
    nameEn: "Makara",
    nameTe: "మకరం (Capricorn)",
    lordEn: "Saturn",
    lordTe: "శని (Shani)",
    element: "Earth (భూమి)",
    symbol: "Sea-Goat (మకరం)",
    color: "from-indigo-600/30 to-violet-950/10",
    glowColor: "rgba(79, 70, 229, 0.4)",
    traits: "Disciplined, hardworking, ambitious, practical, patient, and highly responsible."
  },
  {
    id: 11,
    nameEn: "Kumbha",
    nameTe: "కుంభం (Aquarius)",
    lordEn: "Saturn",
    lordTe: "శని (Shani)",
    element: "Air (వాయువు)",
    symbol: "Water Bearer (కుండ పట్టుకున్న మనుష్యుడు)",
    color: "from-blue-600/30 to-cyan-800/10",
    glowColor: "rgba(37, 99, 235, 0.4)",
    traits: "Humanitarian, original, independent, progressive, intellectual, and innovative."
  },
  {
    id: 12,
    nameEn: "Meena",
    nameTe: "మీనం (Pisces)",
    lordEn: "Jupiter",
    lordTe: "గురుడు (Guru)",
    element: "Water (జలం)",
    symbol: "Two Fishes (చేపల జంట)",
    color: "from-sky-500/30 to-blue-700/10",
    glowColor: "rgba(14, 165, 233, 0.4)",
    traits: "Compassionate, artistic, highly intuitive, dreamer, empathetic, and spiritual."
  }
];
